/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;
import Login.Login;
import Movies.MoviesDetail;
import Movies.MoviesStruck;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class HomeMovies extends javax.swing.JFrame {
public static String name, title, duration, cast, director, studio, tickets;
public static int userID, movieID, phoneNumber;
    /**
     * Creates new form HomeMovies
     */
    public HomeMovies() {
        initComponents();
        Database.MainDB.home(userID, HomeTopUp.total, phoneNumber, name);
        jLabelName.setText(name);
        jLabelUserID.setText(String.valueOf(userID));
        jLabelBalance.setText(String.valueOf(HomeTopUp.total));
        
        HomeTopUp.topup = 0;
        
        ButtonGroup groupmovie = new ButtonGroup();
        groupmovie.add(jRadioButtonMov1);
        groupmovie.add(jRadioButtonMov2);
        groupmovie.add(jRadioButtonMov3);
        groupmovie.add(jRadioButtonMov4);
        
        jButtonMovies.setBackground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupmovie = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelBalance = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonMov1 = new javax.swing.JRadioButton();
        jRadioButtonMov2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonMov3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButtonMov4 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonMovies = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonWallet = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jButtonTickets = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabelUserID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 480));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(449, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 370, 570, 70);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("MOVIES LIST");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Your Balance is Rp.");

        jLabelBalance.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBalance.setText("jLabel16");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabelBalance)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jLabelBalance))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(170, 0, 570, 70);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jRadioButtonMov1.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButtonMov1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMov1.setText("John Wick : Chapter 4");
        jRadioButtonMov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMov1ActionPerformed(evt);
            }
        });

        jRadioButtonMov2.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButtonMov2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMov2.setText("Avatar : The Way of Water");
        jRadioButtonMov2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMov2ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documents\\gambar pj1\\WhatsApp Image 2023-04-12 at 00.02.40.jpeg")); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documents\\gambar pj1\\WhatsApp Image 2023-04-12 at 00.02.29.jpeg")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documents\\gambar pj1\\WhatsApp Image 2023-04-12 at 00.02.42.jpeg")); // NOI18N

        jRadioButtonMov3.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButtonMov3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMov3.setText("Avengers : End Game");
        jRadioButtonMov3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMov3ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Documents\\gambar pj1\\WhatsApp Image 2023-04-12 at 00.02.28.jpeg")); // NOI18N

        jRadioButtonMov4.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButtonMov4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMov4.setText("Pengabdi Setan 2 : Communion");
        jRadioButtonMov4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMov4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonMov3)
                            .addComponent(jRadioButtonMov1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonMov2)
                                    .addComponent(jRadioButtonMov4))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonMov1)
                    .addComponent(jRadioButtonMov2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButtonMov3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonMov4))))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(170, 70, 570, 300);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));

        jButtonMovies.setBackground(new java.awt.Color(255, 255, 51));
        jButtonMovies.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sell.png"))); // NOI18N
        jButtonMovies.setText("Movies");
        jButtonMovies.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Vier");

        jLabel3.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Cinemas");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonWallet.setBackground(new java.awt.Color(255, 255, 51));
        jButtonWallet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonWallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/wallet.png"))); // NOI18N
        jButtonWallet.setText("Wallet");
        jButtonWallet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonWallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonWalletMouseClicked(evt);
            }
        });
        jButtonWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWalletActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 102));
        jLabel9.setText("Welcome,");

        jLabelName.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 102));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Name");
        jLabelName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelName.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonTickets.setBackground(new java.awt.Color(255, 255, 51));
        jButtonTickets.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ticket.png"))); // NOI18N
        jButtonTickets.setText("Tickets");
        jButtonTickets.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTicketsMouseClicked(evt);
            }
        });
        jButtonTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTicketsActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 102));
        jLabel14.setText("Log Out");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabelUserID.setText("jLabel16");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel9))
                                .addComponent(jButtonTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonMovies, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelUserID)))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButtonMovies)
                .addGap(18, 18, 18)
                .addComponent(jButtonWallet)
                .addGap(18, 18, 18)
                .addComponent(jButtonTickets)
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(10, 10, 10)
                .addComponent(jLabelUserID)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, -10, 180, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWalletActionPerformed
        // TODO add your handling code here:;
        userID = Integer.parseInt(jLabelUserID.getText());
        
        HomeTopUp htu = new HomeTopUp();
        htu.setVisible(true);
        htu.pack();
        htu.setLocationRelativeTo(null);
        htu.setDefaultCloseOperation(HomeMovies.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonWalletActionPerformed

    private void jButtonWalletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonWalletMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonWalletMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    userID = Integer.parseInt(jLabelUserID.getText());
    
    if (jRadioButtonMov1.isSelected()) {
        var movie1 = new HomeMovies();
        movie1.movieID = 1;
        movie1.title = "John Wick : Chapter 4";
        movie1.duration = "104 Minutes";
        movie1.cast = "Keanu Reeves, Donnie Yen, Bill Skargard";
        movie1.director = "Chad Stahelski";
        movie1.studio = "1";
        
        MoviesDetail md = new MoviesDetail();
        md.setVisible(true);
        md.pack();
        md.setLocationRelativeTo(null);
        md.setDefaultCloseOperation(HomeMovies.EXIT_ON_CLOSE);
        }
    else if (jRadioButtonMov2.isSelected()) {
        var movie2 = new HomeMovies();
        movie2.movieID = 2;
        movie2.title = "Avatar : The Way of Water";
        movie2.duration = "192 Minutes";
        movie2.cast = "Sam Worthington, Sigourney Weaver";
        movie2.director = "James Cameron";
        movie2.studio = "2";
                
        MoviesDetail md = new MoviesDetail();
        md.setVisible(true);
        md.pack();
        md.setLocationRelativeTo(null);
        md.setDefaultCloseOperation(HomeMovies.EXIT_ON_CLOSE);
        }
    else if (jRadioButtonMov3.isSelected()) {
        var movie3 = new HomeMovies();
        movie3.movieID = 3;
        movie3.title = "Avengers : End Game";
        movie3.duration = "181 Minutes";
        movie3.cast = "Robert Downey Jr., Chris Evans";
        movie3.director = "Anthony Russo";
        movie3.studio = "3";
                
        MoviesDetail md = new MoviesDetail();
        md.setVisible(true);
        md.pack();
        md.setLocationRelativeTo(null);
        md.setDefaultCloseOperation(HomeMovies.EXIT_ON_CLOSE);
        }
    else if (jRadioButtonMov4.isSelected()) {
        var movie4 = new HomeMovies();
        movie4.movieID = 4;
        movie4.title = "Pengabdi Setan 2 : Communion";
        movie4.duration = "119 Minutes";
        movie4.cast = "Tara Barso, Endy Arfian, Nasar Anuz";
        movie4.director = "Joko Anwar";
        movie4.studio = "4";
                
        MoviesDetail md = new MoviesDetail();
        md.setVisible(true);
        md.pack();
        md.setLocationRelativeTo(null);
        md.setDefaultCloseOperation(HomeMovies.EXIT_ON_CLOSE);
        }
    else {
        JOptionPane.showMessageDialog(null, "Please Choose a Movie");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jRadioButtonMov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMov1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMov1ActionPerformed

    private void jRadioButtonMov2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMov2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMov2ActionPerformed

    private void jRadioButtonMov4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMov4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMov4ActionPerformed

    private void jRadioButtonMov3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMov3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMov3ActionPerformed

    private void jButtonTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTicketsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTicketsMouseClicked

    private void jButtonTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTicketsActionPerformed
        // TODO add your handling code here:
        if (MoviesStruck.OrderID != null) {
            userID = Integer.parseInt(jLabelUserID.getText());
            
            MoviesStruck ms = new MoviesStruck();
            ms.setVisible(true);
            ms.pack();
            ms.setLocationRelativeTo(null);
            ms.setDefaultCloseOperation(HomeMovies.EXIT_ON_CLOSE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Oops... you don't have any tickets yet");
        }
    }//GEN-LAST:event_jButtonTicketsActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(HomeMovies.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup groupmovie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMovies;
    private javax.swing.JButton jButtonTickets;
    private javax.swing.JButton jButtonWallet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelBalance;
    public static javax.swing.JLabel jLabelName;
    public static javax.swing.JLabel jLabelUserID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonMov1;
    private javax.swing.JRadioButton jRadioButtonMov2;
    private javax.swing.JRadioButton jRadioButtonMov3;
    private javax.swing.JRadioButton jRadioButtonMov4;
    // End of variables declaration//GEN-END:variables
}
