/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Movies;

import Home.HomeMovies;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MoviesDetail extends javax.swing.JFrame {
    public static String time;

    /**
     * Creates new form MoviesDetail
     */
    public MoviesDetail() {
        initComponents();
        jLabelTitle.setText(HomeMovies.title);
        jLabelDirector.setText(HomeMovies.director);
        jLabelCast.setText(HomeMovies.cast);
        jLabelDuration.setText(HomeMovies.duration);
        
        if(jLabelTitle.getText().equals("John Wick : Chapter 4")){
           jLabelimageJohnW.setVisible(true);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(false);
           jTextArea1.setText("John Wick uncovers a path to\n"+
                                "defeating The High Table.\n" +
                                "But before he can earn his\n" +
                                "freedom, Wick must face off\n" +
                                "against a new enemy with powerful\n" +
                                "alliances across the globe and forces\n" +
                                "that turn old friends into foes.");
        }
        
        else if (jLabelTitle.getText().equals("Avatar : The Way of Water")){
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(true);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(false);
           jTextArea1.setText("“Avatar: The Way of Water” begins\n" +
                              "to tell the story of the Sully family\n" +
                              "(Jake, Neytiri, and their kids), the trouble\n" +
                              "that follows them, the lengths they go\n" +
                              "to keep each other safe, the battles they\n" +
                              "fight to stay alive, and the tragedies\n" +
                              "they endure.");
        }
        
        else if (jLabelTitle.getText().equals("Avengers : End Game")){
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(true);
           jTextArea1.setText("After the devastating events of\n" +
                              "Avengers: Infinity War (2018),\n" +
                              "the universe is in ruins due to\n" +
                              "the efforts of the Mad Titan, Thanos.\n" +
                              "With the help of remaining allies,\n" +
                              "the Avengers must assemble once more\n" +
                              "in order to undo Thanos's actions\n" +
                              "and undo the chaos to the universe,\n" +
                              "no matter what consequences may be\n" +
                              "in store, and no matter who they face");
        }
        else {
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(true);
           jLabelimageAvengers.setVisible(false);
           jTextArea1.setText("When the heavy storm hits, it wasn't\n" +
                              "the storm that a family should fear\n" +
                              "but the people and non-human entities\n" +
                              "who are out for them");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelCast = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelDuration = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelimageAvatar = new javax.swing.JLabel();
        jLabelimageJohnW = new javax.swing.JLabel();
        jLabelimagePengabdiS = new javax.swing.JLabel();
        jLabelimageAvengers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("MOVIE DETAIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(543, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 760, 90);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("jLabel1");
        jPanel2.add(jLabelTitle);
        jLabelTitle.setBounds(400, 40, 302, 25);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "13.00", "15.00", "16.30", "18.00", "20.00" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(470, 200, 230, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Time");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(380, 210, 90, 16);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Director");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(380, 90, 90, 16);

        jLabelDirector.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDirector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDirector.setText("jLabel1");
        jPanel2.add(jLabelDirector);
        jLabelDirector.setBounds(470, 90, 230, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cast");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(380, 130, 90, 16);

        jLabelCast.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCast.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCast.setText("jLabel1");
        jPanel2.add(jLabelCast);
        jLabelCast.setBounds(470, 130, 230, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duration");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(380, 170, 90, 16);

        jLabelDuration.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDuration.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDuration.setText("jLabel1");
        jPanel2.add(jLabelDuration);
        jLabelDuration.setBounds(470, 170, 230, 16);

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Buy Ticket");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(380, 280, 200, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(590, 280, 110, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(190, 40, 180, 230);

        jLabelimageAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-avatar.jpg"))); // NOI18N
        jPanel2.add(jLabelimageAvatar);
        jLabelimageAvatar.setBounds(30, 40, 150, 230);

        jLabelimageJohnW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-johnW.jpg"))); // NOI18N
        jPanel2.add(jLabelimageJohnW);
        jLabelimageJohnW.setBounds(30, 40, 150, 230);

        jLabelimagePengabdiS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-pengabdiS.jpg"))); // NOI18N
        jPanel2.add(jLabelimagePengabdiS);
        jLabelimagePengabdiS.setBounds(30, 40, 150, 230);

        jLabelimageAvengers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg3-avenger.jpg"))); // NOI18N
        jPanel2.add(jLabelimageAvengers);
        jLabelimageAvengers.setBounds(30, 40, 150, 230);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 740, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        time = "";
        HomeMovies.title = "";
        
        HomeMovies hm = new HomeMovies();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(MoviesDetail.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if (jComboBox1.getSelectedItem().equals("Choose")) {
            JOptionPane.showMessageDialog(null, "Please choose your movie time");
        }
        else {
        MoviesSeats ms = new MoviesSeats();
        ms.setVisible(true);
        ms.pack();
        ms.setLocationRelativeTo(null);
        ms.setDefaultCloseOperation(MoviesDetail.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        time = (String) jComboBox1.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCast;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelDuration;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelimageAvatar;
    private javax.swing.JLabel jLabelimageAvengers;
    private javax.swing.JLabel jLabelimageJohnW;
    private javax.swing.JLabel jLabelimagePengabdiS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void jLabelimage(ImageIcon ic) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
