/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Movies;

import Home.HomeMovies;


/**
 *
 * @author User
 */
public class MoviesStruck extends javax.swing.JFrame {
    public static String OrderID;
    /**
     * Creates new form MoviesOrder
     */
    public MoviesStruck() {
        initComponents();
        
        jTextFieldTitle.setText(HomeMovies.title);
        jTextFieldTime.setText(MoviesDetail.time);
        jTextFieldStudio.setText(""+HomeMovies.studio);
        jTextFieldSeats.setText(MoviesSeats.seats);
        
        //Set Movie's Image
        if(jTextFieldTitle.getText().equals("John Wick : Chapter 4")){
           jLabelimageJohnW.setVisible(true);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(false);
        }
        
        else if (jTextFieldTitle.getText().equals("Avatar : The Way of Water")){
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(true);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(false);
        }
        
        else if (jTextFieldTitle.getText().equals("Avengers : End Game")){
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(true);
        }
        else {
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(true);
           jLabelimageAvengers.setVisible(false);
        }
        
        
        jLabelID.setText(String.valueOf(MoviesOrder.order));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldStudio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();
        jTextFieldSeats = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelimageAvatar = new javax.swing.JLabel();
        jLabelimageJohnW = new javax.swing.JLabel();
        jLabelimagePengabdiS = new javax.swing.JLabel();
        jLabelimageAvengers = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 480));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Order ID :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("TICKETS STRUCK");

        jLabelID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 255, 51));
        jLabelID.setText("jLabelID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabelID)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 760, 90);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please scan QR Code to collect your tickets at the theater");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(370, 220, 350, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(29, 86, 130, 20);

        jTextFieldTitle.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextFieldTitle.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTitle.setText("jTextField1");
        jTextFieldTitle.setBorder(null);
        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldTitle);
        jTextFieldTitle.setBounds(30, 30, 374, 32);

        jTextFieldStudio.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldStudio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldStudio.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldStudio.setText("jTextField1");
        jTextFieldStudio.setBorder(null);
        jPanel2.add(jTextFieldStudio);
        jTextFieldStudio.setBounds(29, 258, 180, 25);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(500, 270, 110, 35);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Seats");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(29, 157, 130, 20);

        jTextFieldTime.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldTime.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTime.setText("jTextField1");
        jTextFieldTime.setBorder(null);
        jPanel2.add(jTextFieldTime);
        jTextFieldTime.setBounds(29, 112, 180, 25);

        jTextFieldSeats.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldSeats.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldSeats.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSeats.setText("jTextField1");
        jTextFieldSeats.setBorder(null);
        jPanel2.add(jTextFieldSeats);
        jTextFieldSeats.setBounds(29, 183, 180, 25);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(425, 86, 0, 0);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(413, 86, 0, 140);

        jLabelimageAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-avatar.jpg"))); // NOI18N
        jPanel2.add(jLabelimageAvatar);
        jLabelimageAvatar.setBounds(210, 80, 150, 230);

        jLabelimageJohnW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-johnW.jpg"))); // NOI18N
        jPanel2.add(jLabelimageJohnW);
        jLabelimageJohnW.setBounds(210, 80, 150, 230);

        jLabelimagePengabdiS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-pengabdiS.jpg"))); // NOI18N
        jPanel2.add(jLabelimagePengabdiS);
        jLabelimagePengabdiS.setBounds(210, 80, 150, 230);

        jLabelimageAvengers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg3-avenger.jpg"))); // NOI18N
        jPanel2.add(jLabelimageAvengers);
        jLabelimageAvengers.setBounds(210, 80, 150, 230);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/qr-code2.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(470, 50, 150, 150);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Studio");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(29, 232, 60, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 740, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MoviesOrder.payment = 0;
        
        HomeMovies hm = new HomeMovies();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(MoviesStruck.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesStruck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesStruck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesStruck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesStruck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesStruck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelimageAvatar;
    private javax.swing.JLabel jLabelimageAvengers;
    private javax.swing.JLabel jLabelimageJohnW;
    private javax.swing.JLabel jLabelimagePengabdiS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldSeats;
    private javax.swing.JTextField jTextFieldStudio;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextFieldTitle;
    // End of variables declaration//GEN-END:variables
}
