/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Movies;

import Home.HomeMovies;
import Home.HomeTopUp;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MoviesOrder extends javax.swing.JFrame {
    public static int price, payment;
    protected static int order;

    /**
     * Creates new form MoviesOrder
     */
    public MoviesOrder() {
        initComponents();
        price = 40000;
        
        jTextFieldTitle.setText(HomeMovies.title);
        jTextFieldTime.setText(MoviesDetail.time);
        jTextFieldPrice.setText(""+price);
        jTextFieldSeats.setText(MoviesSeats.seats);
        jTextFieldAmount.setText(""+MoviesSeats.amount);
        
        payment = price * MoviesSeats.amount;
        jTextFieldTotal.setText(""+payment);
        
        if(jTextFieldTitle.getText().equals("John Wick : Chapter 4")){
           jLabelimageJohnW.setVisible(true);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(false);
        }
        
        else if (jTextFieldTitle.getText().equals("Avatar : The Way of Water")){
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(true);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(false);
        }
        
        else if (jTextFieldTitle.getText().equals("Avengers : End Game")){
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(false);
           jLabelimageAvengers.setVisible(true);
        }
        else {
           jLabelimageJohnW.setVisible(false);
           jLabelimageAvatar.setVisible(false);
           jLabelimagePengabdiS.setVisible(true);
           jLabelimageAvengers.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jTextFieldSeats = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelimageAvatar = new javax.swing.JLabel();
        jLabelimageJohnW = new javax.swing.JLabel();
        jLabelimagePengabdiS = new javax.swing.JLabel();
        jLabelimageAvengers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 480));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));
        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("TICKETS DETAIL");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 40, 270, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 760, 90);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Price");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(29, 232, 60, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movie ->");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(29, 30, 105, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(29, 86, 130, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Number of Tickets");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(215, 86, 130, 20);

        jTextFieldTitle.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextFieldTitle.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTitle.setText("jTextField1");
        jTextFieldTitle.setBorder(null);
        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldTitle);
        jTextFieldTitle.setBounds(152, 30, 374, 32);

        jTextFieldPrice.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldPrice.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPrice.setText("jTextField1");
        jTextFieldPrice.setBorder(null);
        jPanel2.add(jTextFieldPrice);
        jTextFieldPrice.setBounds(29, 258, 180, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Price");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(215, 160, 90, 16);

        jTextFieldTotal.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTotal.setText("jTextField1");
        jTextFieldTotal.setBorder(null);
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldTotal);
        jTextFieldTotal.setBounds(215, 183, 180, 25);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(410, 280, 110, 35);

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(590, 280, 108, 35);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Seats");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(29, 157, 130, 20);

        jTextFieldTime.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldTime.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTime.setText("jTextField1");
        jTextFieldTime.setBorder(null);
        jPanel2.add(jTextFieldTime);
        jTextFieldTime.setBounds(29, 112, 180, 25);

        jTextFieldAmount.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldAmount.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldAmount.setText("jTextField1");
        jTextFieldAmount.setBorder(null);
        jPanel2.add(jTextFieldAmount);
        jTextFieldAmount.setBounds(215, 112, 180, 25);

        jTextFieldSeats.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldSeats.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldSeats.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldSeats.setText("jTextField1");
        jTextFieldSeats.setBorder(null);
        jPanel2.add(jTextFieldSeats);
        jTextFieldSeats.setBounds(29, 183, 180, 25);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(425, 86, 0, 0);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(413, 86, 0, 140);

        jLabelimageAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-avatar.jpg"))); // NOI18N
        jPanel2.add(jLabelimageAvatar);
        jLabelimageAvatar.setBounds(540, 30, 150, 230);

        jLabelimageJohnW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-johnW.jpg"))); // NOI18N
        jPanel2.add(jLabelimageJohnW);
        jLabelimageJohnW.setBounds(540, 30, 150, 230);

        jLabelimagePengabdiS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2-pengabdiS.jpg"))); // NOI18N
        jPanel2.add(jLabelimagePengabdiS);
        jLabelimagePengabdiS.setBounds(540, 30, 150, 230);

        jLabelimageAvengers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg3-avenger.jpg"))); // NOI18N
        jPanel2.add(jLabelimageAvengers);
        jLabelimageAvengers.setBounds(540, 30, 150, 230);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 740, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MoviesSeats.seats = "";
        MoviesSeats.amount = 0;
        MoviesDetail.time = "";
        payment = 0;
        
        MoviesSeats ms = new MoviesSeats();
        ms.setVisible(true);
        ms.pack();
        ms.setLocationRelativeTo(null);
        ms.setDefaultCloseOperation(MoviesOrder.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if (payment>HomeTopUp.total) {
            payment = 0;
            MoviesDetail.time = "";
            HomeMovies.title = "";
            MoviesSeats.seats = "";
            MoviesSeats.amount = 0;
               
            JOptionPane.showMessageDialog(null, "Oops... your balance is not enough. Please do the top up first");
            
            HomeTopUp htu = new HomeTopUp();
            htu.setVisible(true);
            htu.pack();
            htu.setLocationRelativeTo(null);
            htu.setDefaultCloseOperation(MoviesOrder.EXIT_ON_CLOSE);
        }
        else {
           HomeTopUp.total += + HomeTopUp.topup - payment;           
           Database.MainDB.order(order, HomeMovies.userID, payment, HomeMovies.movieID, MoviesSeats.amount, MoviesSeats.seats, MoviesDetail.time, HomeMovies.studio);
           Database.MainDB.updateBalance(HomeTopUp.total, HomeMovies.userID);
           
           MoviesStruck ms = new MoviesStruck();
           ms.setVisible(true);
           ms.pack();
           ms.setLocationRelativeTo(null);
           ms.setDefaultCloseOperation(MoviesOrder.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelimageAvatar;
    private javax.swing.JLabel jLabelimageAvengers;
    private javax.swing.JLabel jLabelimageJohnW;
    private javax.swing.JLabel jLabelimagePengabdiS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldSeats;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
