/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Movies;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MoviesSeats extends javax.swing.JFrame {
    protected static String seats;
    protected static int amount;
    protected static JCheckBox[] arrSeats;

    /**
     * Creates new form MoviesSeats
     */
    public MoviesSeats() {
        initComponents();
        seats = "";
        amount = 0;
        
        arrSeats = new JCheckBox[] {jCheckBoxA1, jCheckBoxA2, jCheckBoxA3, jCheckBoxA4, jCheckBoxA5, jCheckBoxA6,
                                    jCheckBoxB1, jCheckBoxB2, jCheckBoxB3, jCheckBoxB4, jCheckBoxB5, jCheckBoxB6,
                                    jCheckBoxC1, jCheckBoxC2, jCheckBoxC3, jCheckBoxC4, jCheckBoxC5, jCheckBoxC6};
        
        jLabel2.setText("Your Number of Tickets are " + amount);
        
        for(int i=0; i<arrSeats.length; i++) {
        arrSeats[i].addActionListener(new ActionListener() {
            @Override
            public void actionPerformed (ActionEvent e) {
                    for(int i=0; i<arrSeats.length; i++) {
                         if (arrSeats[i].isSelected()) {
                             arrSeats[i].setBackground(Color.GREEN);
                         }
                         else {
                             arrSeats[i].setBackground(Color.decode("#333333"));
                         }
                    }
            }
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxA1 = new javax.swing.JCheckBox();
        jCheckBoxA2 = new javax.swing.JCheckBox();
        jCheckBoxA3 = new javax.swing.JCheckBox();
        jCheckBoxA4 = new javax.swing.JCheckBox();
        jCheckBoxA5 = new javax.swing.JCheckBox();
        jCheckBoxA6 = new javax.swing.JCheckBox();
        jCheckBoxB1 = new javax.swing.JCheckBox();
        jCheckBoxB2 = new javax.swing.JCheckBox();
        jCheckBoxB3 = new javax.swing.JCheckBox();
        jCheckBoxB4 = new javax.swing.JCheckBox();
        jCheckBoxB5 = new javax.swing.JCheckBox();
        jCheckBoxB6 = new javax.swing.JCheckBox();
        jCheckBoxC1 = new javax.swing.JCheckBox();
        jCheckBoxC2 = new javax.swing.JCheckBox();
        jCheckBoxC3 = new javax.swing.JCheckBox();
        jCheckBoxC4 = new javax.swing.JCheckBox();
        jCheckBoxC5 = new javax.swing.JCheckBox();
        jCheckBoxC6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 480));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("CHOOSE YOUR BEST VIEW !");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 760, 90);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jCheckBoxA1.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxA1.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxA1.setText("A1 ");
        jCheckBoxA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxA1ActionPerformed(evt);
            }
        });

        jCheckBoxA2.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxA2.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxA2.setText("A2 ");
        jCheckBoxA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxA2ActionPerformed(evt);
            }
        });

        jCheckBoxA3.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxA3.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxA3.setText("A3 ");
        jCheckBoxA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxA3ActionPerformed(evt);
            }
        });

        jCheckBoxA4.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxA4.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxA4.setText("A4 ");
        jCheckBoxA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxA4ActionPerformed(evt);
            }
        });

        jCheckBoxA5.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxA5.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxA5.setText("A5 ");
        jCheckBoxA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxA5ActionPerformed(evt);
            }
        });

        jCheckBoxA6.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxA6.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxA6.setText("A6 ");
        jCheckBoxA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxA6ActionPerformed(evt);
            }
        });

        jCheckBoxB1.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxB1.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxB1.setText("B1 ");
        jCheckBoxB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxB1ActionPerformed(evt);
            }
        });

        jCheckBoxB2.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxB2.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxB2.setText("B2 ");
        jCheckBoxB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxB2ActionPerformed(evt);
            }
        });

        jCheckBoxB3.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxB3.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxB3.setText("B3 ");
        jCheckBoxB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxB3ActionPerformed(evt);
            }
        });

        jCheckBoxB4.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxB4.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxB4.setText("B4 ");
        jCheckBoxB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxB4ActionPerformed(evt);
            }
        });

        jCheckBoxB5.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxB5.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxB5.setText("B5 ");
        jCheckBoxB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxB5ActionPerformed(evt);
            }
        });

        jCheckBoxB6.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxB6.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxB6.setText("B6 ");
        jCheckBoxB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxB6ActionPerformed(evt);
            }
        });

        jCheckBoxC1.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxC1.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxC1.setText("C1 ");
        jCheckBoxC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxC1ActionPerformed(evt);
            }
        });

        jCheckBoxC2.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxC2.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxC2.setText("C2 ");
        jCheckBoxC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxC2ActionPerformed(evt);
            }
        });

        jCheckBoxC3.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxC3.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxC3.setText("C3 ");
        jCheckBoxC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxC3ActionPerformed(evt);
            }
        });

        jCheckBoxC4.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxC4.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxC4.setText("C4 ");
        jCheckBoxC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxC4ActionPerformed(evt);
            }
        });

        jCheckBoxC5.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxC5.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxC5.setText("C5 ");
        jCheckBoxC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxC5ActionPerformed(evt);
            }
        });

        jCheckBoxC6.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBoxC6.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBoxC6.setText("C6 ");
        jCheckBoxC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxC6ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCREEN");

        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Confirm");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Cancel");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jCheckBoxA1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jCheckBoxA2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jCheckBoxA3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(jCheckBoxA4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jCheckBoxA5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jCheckBoxA6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jCheckBoxB1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jCheckBoxB2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jCheckBoxB3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(jCheckBoxB4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jCheckBoxB5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jCheckBoxB6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jCheckBoxC1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jCheckBoxC2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jCheckBoxC3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(jCheckBoxC4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jCheckBoxC5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jCheckBoxC6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 58, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBoxA1)
                        .addComponent(jCheckBoxA2)
                        .addComponent(jCheckBoxA3)
                        .addComponent(jCheckBoxA4)
                        .addComponent(jCheckBoxA5)
                        .addComponent(jCheckBoxA6))
                    .addGap(56, 56, 56)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBoxB1)
                        .addComponent(jCheckBoxB2)
                        .addComponent(jCheckBoxB3)
                        .addComponent(jCheckBoxB4)
                        .addComponent(jCheckBoxB5)
                        .addComponent(jCheckBoxB6))
                    .addGap(56, 56, 56)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBoxC1)
                        .addComponent(jCheckBoxC2)
                        .addComponent(jCheckBoxC3)
                        .addComponent(jCheckBoxC4)
                        .addComponent(jCheckBoxC5)
                        .addComponent(jCheckBoxC6))
                    .addGap(36, 36, 36)
                    .addComponent(jLabel2)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 740, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxA1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxA1.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxA1ActionPerformed

    private void jCheckBoxA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxA2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxA2.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxA2ActionPerformed

    private void jCheckBoxA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxA3ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxA3.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxA3ActionPerformed

    private void jCheckBoxA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxA4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxA4.isSelected()) {
            amount += + 1;
            jCheckBoxA4.setBackground(Color.GREEN);
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxA4ActionPerformed

    private void jCheckBoxA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxA5ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxA5.isSelected()) {
            amount += + 1;
            jCheckBoxA5.setBackground(Color.GREEN);
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxA5ActionPerformed

    private void jCheckBoxA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxA6ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxA6.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxA6ActionPerformed

    private void jCheckBoxB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxB1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxB1.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxB1ActionPerformed

    private void jCheckBoxB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxB2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxB2.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxB2ActionPerformed

    private void jCheckBoxB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxB3ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxB3.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxB3ActionPerformed

    private void jCheckBoxB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxB4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxB4.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxB4ActionPerformed

    private void jCheckBoxB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxB5ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxB5.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxB5ActionPerformed

    private void jCheckBoxB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxB6ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxB6.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxB6ActionPerformed

    private void jCheckBoxC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxC1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxC1.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxC1ActionPerformed

    private void jCheckBoxC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxC2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxC2.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxC2ActionPerformed

    private void jCheckBoxC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxC3ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxC3.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxC3ActionPerformed

    private void jCheckBoxC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxC4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxC4.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxC4ActionPerformed

    private void jCheckBoxC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxC5ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxC5.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxC5ActionPerformed

    private void jCheckBoxC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxC6ActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxC6.isSelected()) {
            amount += + 1;
        }
        else {
            amount += - 1;
        }
        jLabel2.setText("Your Number of Tickets are " + amount);
    }//GEN-LAST:event_jCheckBoxC6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(amount<1) {
           JOptionPane.showMessageDialog(null, "Please Select The Seats");
        }
        else {
         for(int i=0; i<arrSeats.length; i++) {
            if (arrSeats[i].isSelected()) {
                seats += arrSeats[i].getText();
                arrSeats[i].getSelectedIcon();
            }
         }
        
        MoviesOrder mo = new MoviesOrder();
        mo.setVisible(true);
        mo.pack();
        mo.setLocationRelativeTo(null);
        mo.setDefaultCloseOperation(MoviesSeats.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        amount = 0;
        MoviesDetail.time = "";
        
        for(int i=0; i<arrSeats.length; i++) {
        arrSeats[i].setSelected(false);
        }
        
        MoviesDetail md = new MoviesDetail();
        md.setVisible(true);
        md.pack();
        md.setLocationRelativeTo(null);
        md.setDefaultCloseOperation(MoviesSeats.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviesSeats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxA1;
    private javax.swing.JCheckBox jCheckBoxA2;
    private javax.swing.JCheckBox jCheckBoxA3;
    private javax.swing.JCheckBox jCheckBoxA4;
    private javax.swing.JCheckBox jCheckBoxA5;
    private javax.swing.JCheckBox jCheckBoxA6;
    private javax.swing.JCheckBox jCheckBoxB1;
    private javax.swing.JCheckBox jCheckBoxB2;
    private javax.swing.JCheckBox jCheckBoxB3;
    private javax.swing.JCheckBox jCheckBoxB4;
    private javax.swing.JCheckBox jCheckBoxB5;
    private javax.swing.JCheckBox jCheckBoxB6;
    private javax.swing.JCheckBox jCheckBoxC1;
    private javax.swing.JCheckBox jCheckBoxC2;
    private javax.swing.JCheckBox jCheckBoxC3;
    private javax.swing.JCheckBox jCheckBoxC4;
    private javax.swing.JCheckBox jCheckBoxC5;
    private javax.swing.JCheckBox jCheckBoxC6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
